### PR TITLE
Add .cmake & CMakeLists.txt

### PR DESCRIPTION
**Pull request by kammce**

### CODE REVIEW

**Comment by mbrukman** [comment]
Hey @kammce, thanks for the PR! Would you mind removing the emoji from the commit message? Totally fine with the creativity on the PR titles on the GitHub repo, but trying to keep the commit log readable and not distracting.

Also, I am slowly working (in the background, so no PRs yet) on a rewrite of the tool from shell/Python scripts into a stand-alone Go binary, so I'd need to ensure it has parity with the current shell scripts. To that end, would you mind adding one or more tests for the new file extnesions? It's easy to do, as described in https://github.com/mbrukman/autogen/#developing -- it will generate the output and error logs for you if you just provide the input command lines.

Thanks!

**Comment by kammce** [comment]
Bump

**Comment by kammce** [comment]
@mbrukman I think I've done what was required of me. Can you take a look at this PR?

**Comment by mbrukman** [comment]
@kammce — apologies for the delay! I missed this earlier. LGTM!

Thanks again for your contribution.

**Pull request merged**
